"""vacancy country and work formats

Revision ID: 582ff1f02df1
Revises: 3406da5356e8
Create Date: 2026-09-24 10:08:16.716816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '582ff1f02df1'
down_revision: Union[str, Sequence[str], None] = '3406da5356e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('country', sa.Text(), nullable=True))
    op.add_column('vacancies', sa.Column('work_formats', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False))
    # ### end Alembic commands ###

    # No backfill. `country` could be derived from the JSON-LD already in
    # `raw`, but only in the site's own language, and `work_formats` comes from
    # the page markup and was never stored at all — so existing rows are
    # re-scraped rather than half-filled.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'work_formats')
    op.drop_column('vacancies', 'country')
    # ### end Alembic commands ###
