"""best angle per vacancy

Revision ID: b719833b39fd
Revises: 582ff1f02df1
Create Date: 2026-09-24 14:52:04.428282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b719833b39fd'
down_revision: Union[str, Sequence[str], None] = '582ff1f02df1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_results', sa.Column('best_angle', sa.String(length=32), nullable=False))
    op.add_column('match_results', sa.Column('best_angle_confidence', sa.Double(), nullable=False))
    # ### end Alembic commands ###

    # Autogenerate does not diff CheckConstraint changes (architecture §11), so
    # widening the range check to the new column is hand-written.
    op.drop_constraint('ck_match_results_probabilities_in_range', 'match_results')
    op.create_check_constraint(
        'probabilities_in_range',
        'match_results',
        'overall_fit_score BETWEEN 0 AND 1 AND is_qualified_noul BETWEEN 0 AND 1 '
        'AND overall_fit_confidence BETWEEN 0 AND 1 AND top_gap_confidence BETWEEN 0 AND 1 '
        'AND best_angle_confidence BETWEEN 0 AND 1',
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_match_results_probabilities_in_range', 'match_results')
    op.create_check_constraint(
        'probabilities_in_range',
        'match_results',
        'overall_fit_score BETWEEN 0 AND 1 AND is_qualified_noul BETWEEN 0 AND 1 '
        'AND overall_fit_confidence BETWEEN 0 AND 1 AND top_gap_confidence BETWEEN 0 AND 1',
    )
    op.drop_column('match_results', 'best_angle_confidence')
    op.drop_column('match_results', 'best_angle')
    # ### end Alembic commands ###
