"""vacancies

Revision ID: d0f5719cd1b6
Revises: 
Create Date: 2026-09-23 22:26:57.397413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0f5719cd1b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('salary_raw', sa.Text(), nullable=True),
    sa.Column('experience_raw', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetch_attempts', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('fetch_error', sa.Text(), nullable=True),
    sa.Column('delisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('starred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hidden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vacancies')),
    sa.UniqueConstraint('source', 'external_id', name='uq_vacancies_source_external_id')
    )
    op.create_index('ix_vacancies_fetch_queue', 'vacancies', ['first_seen_at'], unique=False, postgresql_where=sa.text('fetched_at IS NULL AND delisted_at IS NULL AND fetch_attempts < 3'))
    op.create_index('ix_vacancies_url', 'vacancies', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vacancies_url', table_name='vacancies')
    op.drop_index('ix_vacancies_fetch_queue', table_name='vacancies', postgresql_where=sa.text('fetched_at IS NULL AND delisted_at IS NULL AND fetch_attempts < 3'))
    op.drop_table('vacancies')
    # ### end Alembic commands ###
